# Codecov configuration
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success
    patch:
      default:
        target: 80%

  ignore:
    - "backend/tests/*"
    - "frontend/src/tests/*"
    - "backend/migrations/*"
    - "**/__pycache__/**"
    - "**/node_modules/**"
    - "frontend/dist/**"
    - "frontend/build/**"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

github_checks:
  annotations: true