#!/usr/bin/env python3
"""
Unit Tests for XML Writer Structure

Tests that the FCP7XMLWriter generates correct XML structure for DaVinci Resolve:
- No <project> wrapper
- No <children> wrapper
- <sequence> directly under <xmeml>
- Canonical file block pattern (first clip full, others reference)

Author: EasyEdit v2
Date: 2025-11-27
"""

import sys
import os
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

# Add backend to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from models.timeline import Timeline, Track, Clip
from parsers.xml_writer import FCP7XMLWriter


class TestXMLWriterStructure(unittest.TestCase):
    """Test XML structure generated by FCP7XMLWriter"""

    def setUp(self):
        """Set up test fixtures"""
        self.writer = FCP7XMLWriter()

    def create_sample_timeline(self, num_clips: int = 3) -> Timeline:
        """Create a sample timeline for testing"""
        timeline = Timeline(
            name="Test Timeline",
            duration=100.0,
            frame_rate=30.0,
            sample_rate=48000
        )

        # Create video track with multiple clips
        video_track = Track(index=0, name="Video 1", track_type="video")

        for i in range(num_clips):
            clip = Clip(
                name=f"Clip {i+1}",
                start_time=i * 10.0,
                end_time=(i + 1) * 10.0,
                duration=10.0,
                track_index=0,
                enabled=True
            )
            video_track.add_clip(clip)

        timeline.add_track(video_track)

        # Add canonical file block (simulating parsed DRT)
        timeline.canonical_file_block = {
            'file_id': 'file-1',
            'name': 'Test_Audio.wav',
            'pathurl': 'file://localhost/C:/path/to/Test_Audio.wav',
            'duration_frames': 3000,
            'samplecharacteristics': {
                'width': 1920,
                'height': 1080
            },
            'audio': {
                'channelcount': 2
            },
            'timecode': {
                'string': '01:00:00:00',
                'displayformat': 'NDF'
            }
        }

        return timeline

    def test_xml_hierarchy_no_project_wrapper(self):
        """Test that XML has no <project> or <children> wrappers"""
        print("\n[TEST 1] XML Hierarchy - No Project Wrapper")

        timeline = self.create_sample_timeline(num_clips=1)
        xml_content = self.writer.generate_fcp7_xml(timeline)

        # Parse XML
        root = ET.fromstring(xml_content)

        # Check 1: Root is xmeml
        self.assertEqual(root.tag, 'xmeml', "Root element must be <xmeml>")
        self.assertEqual(root.get('version'), '5', "xmeml version must be 5")
        print("  [OK] Root is <xmeml version='5'>")

        # Check 2: No <project> tags anywhere
        project_tags = root.findall('.//project')
        self.assertEqual(len(project_tags), 0, "XML must not contain <project> tags")
        print("  [OK] No <project> wrapper found")

        # Check 3: No <children> tags anywhere
        children_tags = root.findall('.//children')
        self.assertEqual(len(children_tags), 0, "XML must not contain <children> tags")
        print("  [OK] No <children> wrapper found")

        # Check 4: <sequence> is direct child of <xmeml>
        sequences = root.findall('./sequence')
        self.assertEqual(len(sequences), 1, "Must have exactly 1 <sequence> as direct child")
        print("  [OK] <sequence> is direct child of <xmeml>")

        print("  [PASS] XML hierarchy test passed\n")

    def test_canonical_file_block_pattern(self):
        """Test canonical file block pattern: first clip full, others reference"""
        print("\n[TEST 2] Canonical File Block Pattern")

        timeline = self.create_sample_timeline(num_clips=3)
        xml_content = self.writer.generate_fcp7_xml(timeline)

        # Parse XML
        root = ET.fromstring(xml_content)

        # Find all clipitems in video track
        clipitems = root.findall('.//video/track/clipitem')
        self.assertEqual(len(clipitems), 3, "Should have 3 clipitems")
        print(f"  [OK] Found {len(clipitems)} clipitems")

        # Check first clip - should have full file block
        first_clip_file = clipitems[0].find('./file')
        self.assertIsNotNone(first_clip_file, "First clip must have <file> element")

        # Check if it's a full block (has children) or reference (no children)
        file_children = list(first_clip_file)
        self.assertGreater(len(file_children), 0, "First clip must have full file block with children")
        print(f"  [OK] First clip has full file block ({len(file_children)} children)")

        # Validate first clip has required elements
        self.assertIsNotNone(first_clip_file.find('./name'), "First clip file must have <name>")
        self.assertIsNotNone(first_clip_file.find('./pathurl'), "First clip file must have <pathurl>")
        self.assertIsNotNone(first_clip_file.find('./duration'), "First clip file must have <duration>")
        print("  [OK] First clip file block has name, pathurl, duration")

        # Check subsequent clips - should have reference only
        for i, clipitem in enumerate(clipitems[1:], start=2):
            clip_file = clipitem.find('./file')
            self.assertIsNotNone(clip_file, f"Clip {i} must have <file> element")

            # Check if it's a reference (no children, just id attribute)
            file_children = list(clip_file)
            self.assertEqual(len(file_children), 0, f"Clip {i} should have reference-only file (self-closing)")
            self.assertIsNotNone(clip_file.get('id'), f"Clip {i} file must have id attribute")
            print(f"  [OK] Clip {i} has reference-only file (id='{clip_file.get('id')}')")

        # Verify all references point to same file ID
        first_file_id = first_clip_file.get('id')
        for i, clipitem in enumerate(clipitems[1:], start=2):
            clip_file = clipitem.find('./file')
            self.assertEqual(clip_file.get('id'), first_file_id,
                           f"Clip {i} must reference same file ID as first clip")

        print(f"  [OK] All clips reference same file ID: {first_file_id}")
        print("  [PASS] Canonical file block pattern test passed\n")

    def test_davinci_resolve_structure_compatibility(self):
        """Test that structure matches DaVinci Resolve export format"""
        print("\n[TEST 3] DaVinci Resolve Structure Compatibility")

        timeline = self.create_sample_timeline(num_clips=2)
        xml_content = self.writer.generate_fcp7_xml(timeline)

        # Check XML declaration
        self.assertTrue(xml_content.startswith('<?xml version="1.0"'),
                       "XML must start with declaration")
        print("  [OK] XML declaration present")

        # Check DOCTYPE
        self.assertIn('<!DOCTYPE xmeml>', xml_content, "XML must have DOCTYPE")
        print("  [OK] DOCTYPE present")

        # Parse and validate structure
        root = ET.fromstring(xml_content)

        # Check sequence structure
        sequence = root.find('./sequence')
        self.assertIsNotNone(sequence, "Must have <sequence>")
        self.assertIsNotNone(sequence.get('id'), "Sequence must have id")
        print(f"  [OK] Sequence present (id='{sequence.get('id')}')")

        # Check sequence children (DaVinci Resolve order)
        seq_name = sequence.find('./name')
        seq_duration = sequence.find('./duration')
        seq_rate = sequence.find('./rate')
        seq_media = sequence.find('./media')

        self.assertIsNotNone(seq_name, "Sequence must have <name>")
        self.assertIsNotNone(seq_duration, "Sequence must have <duration>")
        self.assertIsNotNone(seq_rate, "Sequence must have <rate>")
        self.assertIsNotNone(seq_media, "Sequence must have <media>")
        print("  [OK] Sequence has name, duration, rate, media")

        # Check media structure
        video = seq_media.find('./video')
        self.assertIsNotNone(video, "Media must have <video>")
        print("  [OK] Media has video element")

        # Check video tracks come before format (DaVinci structure)
        video_children = list(video)
        self.assertGreater(len(video_children), 0, "Video must have children")

        # First children should be tracks
        first_child = video_children[0]
        self.assertEqual(first_child.tag, 'track', "First video child should be <track>")
        print("  [OK] Video tracks precede format element")

        print("  [PASS] DaVinci Resolve structure compatibility test passed\n")

    def test_empty_timeline_structure(self):
        """Test that empty timeline generates valid structure"""
        print("\n[TEST 4] Empty Timeline Structure")

        timeline = Timeline(
            name="Empty Timeline",
            duration=0.0,
            frame_rate=30.0,
            sample_rate=48000
        )

        xml_content = self.writer.generate_fcp7_xml(timeline)

        # Parse XML
        root = ET.fromstring(xml_content)

        # Check structure is still correct
        self.assertEqual(root.tag, 'xmeml')
        sequences = root.findall('./sequence')
        self.assertEqual(len(sequences), 1)
        print("  [OK] Empty timeline generates valid structure")

        # Should have no project wrapper
        project_tags = root.findall('.//project')
        self.assertEqual(len(project_tags), 0)
        print("  [OK] Empty timeline has no project wrapper")

        print("  [PASS] Empty timeline structure test passed\n")

    def test_multiple_tracks_structure(self):
        """Test structure with multiple video and audio tracks"""
        print("\n[TEST 5] Multiple Tracks Structure")

        timeline = Timeline(
            name="Multi-Track Timeline",
            duration=100.0,
            frame_rate=30.0,
            sample_rate=48000
        )

        # Add multiple video tracks
        for track_num in range(2):
            video_track = Track(index=track_num, name=f"Video {track_num + 1}", track_type="video")
            clip = Clip(
                name=f"Video_Clip_{track_num + 1}",
                start_time=0.0,
                end_time=10.0,
                duration=10.0,
                track_index=track_num,
                enabled=True
            )
            video_track.add_clip(clip)
            timeline.add_track(video_track)

        # Add audio track
        audio_track = Track(index=2, name="Audio 1", track_type="audio")
        audio_clip = Clip(
            name="Audio_Clip_1",
            start_time=0.0,
            end_time=10.0,
            duration=10.0,
            track_index=2,
            enabled=True
        )
        audio_track.add_clip(audio_clip)
        timeline.add_track(audio_track)

        # Set canonical block
        timeline.canonical_file_block = {
            'file_id': 'file-1',
            'name': 'Test.wav',
            'pathurl': 'file://localhost/Test.wav',
            'duration_frames': 300
        }

        xml_content = self.writer.generate_fcp7_xml(timeline)
        root = ET.fromstring(xml_content)

        # Verify structure
        self.assertEqual(root.tag, 'xmeml')
        self.assertEqual(len(root.findall('.//project')), 0)
        print("  [OK] Multi-track timeline has correct structure")

        # Check video and audio sections
        media = root.find('.//media')
        video = media.find('./video')
        audio = media.find('./audio')

        self.assertIsNotNone(video, "Media must have video")
        self.assertIsNotNone(audio, "Media must have audio")

        video_tracks = video.findall('./track')
        audio_tracks = audio.findall('./track')

        self.assertEqual(len(video_tracks), 2, "Should have 2 video tracks")
        self.assertEqual(len(audio_tracks), 1, "Should have 1 audio track")
        print(f"  [OK] Found {len(video_tracks)} video tracks, {len(audio_tracks)} audio track")

        print("  [PASS] Multiple tracks structure test passed\n")


def run_tests():
    """Run all tests"""
    print("\n" + "="*60)
    print("XML Writer Structure Unit Tests")
    print("="*60)

    # Create test suite
    loader = unittest.TestLoader()
    suite = loader.loadTestsFromTestCase(TestXMLWriterStructure)

    # Run tests
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)

    # Summary
    print("\n" + "="*60)
    print("Test Summary")
    print("="*60)
    print(f"Tests run: {result.testsRun}")
    print(f"Successes: {result.testsRun - len(result.failures) - len(result.errors)}")
    print(f"Failures: {len(result.failures)}")
    print(f"Errors: {len(result.errors)}")

    if result.wasSuccessful():
        print("\n[SUCCESS] All tests passed!")
    else:
        print("\n[FAILURE] Some tests failed")

    print("="*60 + "\n")

    return result.wasSuccessful()


if __name__ == '__main__':
    success = run_tests()
    sys.exit(0 if success else 1)
